[package]
name = "weatherapp"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.4", features = ["image"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9"